#!/usr/bin/env python
# -*- coding: utf-8 -*-

platforms = [
    'Acorn',
    'Alambik',
    'Amiga AGA',
    'Amiga OCS/ECS',
    'Amiga PPC/RTG',
    'Amstrad CPC',
    'Amstrad Plus',
    'Android',
    'Apple II',
    'Apple II GS',
    'Atari Falcon 030',
    'Atari Jaguar',
    'Atari Lynx',
    'Atari ST',
    'Atari STe',
    'Atari TT 030',
    'Atari VCS',
    'Atari XL/XE',
    'BBC Micro',
    'BeOS',
    'BK-0010/11M',
    'C16/116/plus4',
    'C64 DTV',
    'Commodore 128',
    'Commodore 64',
    'Dreamcast',
    'Enterprise',
    'Flash',
    'FreeBSD',
    'Gameboy',
    'Gameboy Advance',
    'Gameboy Color',
    'Gamecube',
    'GamePark GP2X',
    'GamePark GP32',
    'Intellivision',
    'iOS',
    'Java',
    'JavaScript',
    'Linux',
    'MacOS',
    'MacOSX',
    'MacOSX Intel',
    'mIRC',
    'Mobile Phone',
    'MS-Dos',
    'MS-Dos/gus',
    'MSX',
    'MSX 2',
    'MSX 2 plus',
    'MSX Turbo-R',
    'NEC TurboGrafx/PC Engine',
    'NeoGeo Pocket',
    'NES/Famicom',
    'Nintendo 64',
    'Nintendo DS',
    'Nintendo Wii',
    'Oric',
    'PalmOS',
    'PHP',
    'Playstation',
    'Playstation 2',
    'Playstation 3',
    'Playstation Portable',
    'PocketPC',
    'Pokemon Mini',
    'Raspberry Pi',
    'SAM Coupé',
    'SEGA Game Gear',
    'SEGA Genesis/Mega Drive',
    'SEGA Master System',
    'SGI/IRIX',
    'Sharp MZ',
    'SNES/Super Famicom',
    'Solaris',
    'Spectravideo 3x8',
    'Thomson',
    'TI-8x',
    'TRS-80/CoCo',
    'Vectrex',
    'VIC 20',
    'Virtual Boy',
    'Wild',
    'Windows',
    'Wonderswan',
    'XBOX',
    'XBOX 360',
    'ZX Enhanced',
    'ZX Spectrum', 
    'ZX-81']
